// <auto-generated />
using System;
using LiveAuction.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LiveAuction.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AuctionDbContext))]
    [Migration("20261005151042_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LiveAuction.Domain.Auctions.Auction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BidCount")
                        .HasColumnType("integer")
                        .HasColumnName("bid_count");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("CurrentPriceInPaise")
                        .HasColumnType("bigint")
                        .HasColumnName("current_price_in_paise");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<long?>("LeaderMaxInPaise")
                        .HasColumnType("bigint")
                        .HasColumnName("leader_max_in_paise");

                    b.Property<Guid?>("LeadingBidderId")
                        .HasColumnType("uuid")
                        .HasColumnName("leading_bidder_id");

                    b.Property<long?>("ReservePriceInPaise")
                        .HasColumnType("bigint")
                        .HasColumnName("reserve_price_in_paise");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_id");

                    b.Property<long>("StartingPriceInPaise")
                        .HasColumnType("bigint")
                        .HasColumnName("starting_price_in_paise");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("title");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_auctions");

                    b.HasIndex("EndsAt")
                        .HasDatabaseName("ix_auctions_live_ends_at")
                        .HasFilter("status = 'Live'");

                    b.HasIndex("SellerId")
                        .HasDatabaseName("ix_auctions_seller_id");

                    b.HasIndex("StartsAt")
                        .HasDatabaseName("ix_auctions_scheduled_starts_at")
                        .HasFilter("status = 'Scheduled'");

                    b.HasIndex("Title")
                        .HasDatabaseName("ix_auctions_title_trigram");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Title"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Title"), new[] { "gin_trgm_ops" });

                    b.ToTable("auctions", (string)null);
                });

            modelBuilder.Entity("LiveAuction.Domain.Bidding.Bid", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("AmountInPaise")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_in_paise");

                    b.Property<Guid>("AuctionId")
                        .HasColumnType("uuid")
                        .HasColumnName("auction_id");

                    b.Property<Guid>("BidderId")
                        .HasColumnType("uuid")
                        .HasColumnName("bidder_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset>("PlacedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("placed_at");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.HasKey("Id")
                        .HasName("pk_bids");

                    b.HasIndex("AuctionId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ix_bids_auction_id_sequence");

                    b.HasIndex("BidderId", "AuctionId")
                        .HasDatabaseName("ix_bids_bidder_id_auction_id");

                    b.ToTable("bids", (string)null);
                });

            modelBuilder.Entity("LiveAuction.Domain.Bidding.Bid", b =>
                {
                    b.HasOne("LiveAuction.Domain.Auctions.Auction", null)
                        .WithMany()
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bids_auctions_auction_id");
                });
#pragma warning restore 612, 618
        }
    }
}
